<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Functions</title>
    <link rel="stylesheet" href="../helpers.css">
</head>

<body>

    <script src="../helpers.js"></script>
    <script>

        const promise1 = new Promise((resolve, reject) => {
            reject("Explicitly reject a promise!");
        });

        promise1.then(
            () => fail("Succes, won't be called!"),
            (error) => pass("A promise was explicitly rejected.")
        );

        const promise2 = new Promise((resolve, reject) => {
            reject("Explicitly reject a promise!");
        });
        promise2
            .then(() => fail("Success, won't be called!"))
            .catch(() => pass("This promise was also rejected."));

    </script>

</body>

</html>